<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $data = [
            // Dewi Titania Randa
            ['user_id' => 32, 'destination_id' => 181, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 184, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 185, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 186, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 187, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 188, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 210, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 214, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 194, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 32, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Rafli Fachry
            ['user_id' => 33, 'destination_id' => 181, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 183, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 184, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 185, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 186, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 187, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 188, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 189, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 210, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 212, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 214, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 216, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 218, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 190, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 191, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 194, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 33, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Aditya
            ['user_id' => 34, 'destination_id' => 181, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 184, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 185, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 186, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 188, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 189, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 211, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 214, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 218, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 194, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 34, 'destination_id' => 196, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Dela
            ['user_id' => 35, 'destination_id' => 181, 'rating' => 1, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 183, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 184, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 185, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 186, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 187, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 188, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 214, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 215, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 216, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 218, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 194, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 35, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Ulan
            ['user_id' => 36, 'destination_id' => 181, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 184, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 186, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 188, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 189, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 214, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 215, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 216, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 218, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 194, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 36, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Ajeng
            ['user_id' => 37, 'destination_id' => 181, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 183, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 184, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 186, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 187, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 188, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 214, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 215, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 190, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 194, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 37, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Muhammad Azriel Saktiawan
            ['user_id' => 38, 'destination_id' => 181, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 184, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 186, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 188, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 214, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 215, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 194, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 38, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Ahmad Fadli Ramadhan
            ['user_id' => 39, 'destination_id' => 181, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 184, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 186, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 187, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 188, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 214, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 215, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 216, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 218, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 194, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 39, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Icang
            ['user_id' => 40, 'destination_id' => 181, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 184, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 186, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 188, 'rating' => 1, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 189, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 210, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 214, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 216, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 218, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 190, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 191, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 194, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 40, 'destination_id' => 196, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Marianne Riani Mundeh
            ['user_id' => 41, 'destination_id' => 181, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 184, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 185, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 186, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 188, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 189, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 214, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 216, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 218, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 194, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 41, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Febriansyah
            ['user_id' => 42, 'destination_id' => 181, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 183, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 184, 'rating' => 1, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 186, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 187, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 188, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 189, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 214, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 215, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 218, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 190, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 191, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 194, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 42, 'destination_id' => 196, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Iman
            ['user_id' => 43, 'destination_id' => 181, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 183, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 184, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 186, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 187, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 188, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 214, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 215, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 216, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 218, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 194, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 43, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Wendhy
            ['user_id' => 44, 'destination_id' => 181, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 183, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 184, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 186, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 188, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 189, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 210, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 214, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 190, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 191, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 194, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 44, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Usamah
            ['user_id' => 45, 'destination_id' => 181, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 183, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 184, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 185, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 186, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 187, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 188, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 212, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 213, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 214, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 215, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 190, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 191, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 194, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 45, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Rifan
            ['user_id' => 46, 'destination_id' => 181, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 183, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 184, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 185, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 186, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 187, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 188, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 189, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 46, 'destination_id' => 210, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 46, 'destination_id' => 211, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 46, 'destination_id' => 212, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 46, 'destination_id' => 213, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 46, 'destination_id' => 214, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 194, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 46, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Dhani
            // ['user_id' => 47, 'destination_id' => 181, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 47, 'destination_id' => 183, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 184, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 186, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 187, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 188, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 189, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 211, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 212, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 213, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 214, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 47, 'destination_id' => 190, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 47, 'destination_id' => 191, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 47, 'destination_id' => 194, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 47, 'destination_id' => 196, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Yulinda Rizky 
            ['user_id' => 48, 'destination_id' => 181, 'rating' => 1, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 184, 'rating' => 1, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 185, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 186, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 188, 'rating' => 1, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 48, 'destination_id' => 189, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 48, 'destination_id' => 210, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 48, 'destination_id' => 211, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 48, 'destination_id' => 212, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 48, 'destination_id' => 213, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 214, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 215, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 216, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 218, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 194, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 48, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Ayudri
            ['user_id' => 49, 'destination_id' => 181, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 184, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 185, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 186, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 188, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 49, 'destination_id' => 210, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 49, 'destination_id' => 211, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 49, 'destination_id' => 212, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 49, 'destination_id' => 213, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 49, 'destination_id' => 214, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 190, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 191, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 194, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 49, 'destination_id' => 196, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Ade
            ['user_id' => 50, 'destination_id' => 181, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 183, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 184, 'rating' => 2, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 185, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 186, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 187, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 188, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 189, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 210, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 211, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 212, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 213, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 214, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 215, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 50, 'destination_id' => 216, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 50, 'destination_id' => 218, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 50, 'destination_id' => 190, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 50, 'destination_id' => 191, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 50, 'destination_id' => 194, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 50, 'destination_id' => 196, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],

            // Muhammad Asyraf
            ['user_id' => 51, 'destination_id' => 181, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 183, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 184, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 185, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 186, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 187, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 188, 'rating' => 3, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 189, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 210, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 51, 'destination_id' => 211, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 51, 'destination_id' => 212, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 51, 'destination_id' => 213, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 51, 'destination_id' => 214, 'rating' => 0, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            // ['user_id' => 51, 'destination_id' => 215, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 216, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 218, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 190, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 191, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 194, 'rating' => 4, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
            ['user_id' => 51, 'destination_id' => 196, 'rating' => 5, 'comment' => null, 'created_at' => now(), 'updated_at' => null],
        ];

        DB::table('reviews')->insert($data);
    }
}
